# coding: utf-8

"""
    Aces Service API

    API Specification for Aces Services for blockchain interoperability. 

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Capacity(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'value': 'float',
        'unit': 'str',
        'display_value': 'str'
    }

    attribute_map = {
        'value': 'value',
        'unit': 'unit',
        'display_value': 'displayValue'
    }

    def __init__(self, value=None, unit=None, display_value=None):
        """
        Capacity - a model defined in Swagger
        """

        self._value = None
        self._unit = None
        self._display_value = None
        self.discriminator = None

        if value is not None:
          self.value = value
        if unit is not None:
          self.unit = unit
        if display_value is not None:
          self.display_value = display_value

    @property
    def value(self):
        """
        Gets the value of this Capacity.
        The capacity value.

        :return: The value of this Capacity.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this Capacity.
        The capacity value.

        :param value: The value of this Capacity.
        :type: float
        """

        self._value = value

    @property
    def unit(self):
        """
        Gets the unit of this Capacity.
        The unit type of given capacity, i.e. \"ETH\".

        :return: The unit of this Capacity.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """
        Sets the unit of this Capacity.
        The unit type of given capacity, i.e. \"ETH\".

        :param unit: The unit of this Capacity.
        :type: str
        """

        self._unit = unit

    @property
    def display_value(self):
        """
        Gets the display_value of this Capacity.
        The formatted display value of the capacity, i.e. \"250.00 ETH\"

        :return: The display_value of this Capacity.
        :rtype: str
        """
        return self._display_value

    @display_value.setter
    def display_value(self, display_value):
        """
        Sets the display_value of this Capacity.
        The formatted display value of the capacity, i.e. \"250.00 ETH\"

        :param display_value: The display_value of this Capacity.
        :type: str
        """

        self._display_value = display_value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Capacity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
