<?php
/**
 * Feature
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArkAces\ServiceClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability.
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ArkAces\ServiceClient\Model;
use \ArkAces\ServiceClient\ObjectSerializer;

/**
 * Feature Class Doc Comment
 *
 * @category Class
 * @package  ArkAces\ServiceClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Feature
{
    /**
     * Possible values of this enum
     */
    const ARK_SMARTBRIDGE_PAYABLE = 'arkSmartbridgePayable';
    const ARK_RETURNABLE = 'arkReturnable';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ARK_SMARTBRIDGE_PAYABLE,
            self::ARK_RETURNABLE,
        ];
    }
}


