/**
 * Aces Service API
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Argument model module.
* @module model/Argument
* @version 0.1.0
*/
export default class Argument {
    /**
    * Constructs a new <code>Argument</code>.
    * @alias module:model/Argument
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Argument</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Argument} obj Optional instance to populate.
    * @return {module:model/Argument} The populated <code>Argument</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Argument();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
        }
        return obj;
    }

    /**
    * Argument name matching a parameter in service contract schema.
    * @member {String} name
    */
    name = undefined;
    /**
    * Arugment value.
    * @member {Object} value
    */
    value = undefined;








}


