/**
 * Aces Service API
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Capacity model module.
* @module model/Capacity
* @version 0.1.0
*/
export default class Capacity {
    /**
    * Constructs a new <code>Capacity</code>.
    * @alias module:model/Capacity
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Capacity</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Capacity} obj Optional instance to populate.
    * @return {module:model/Capacity} The populated <code>Capacity</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Capacity();

            
            
            

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('displayValue')) {
                obj['displayValue'] = ApiClient.convertToType(data['displayValue'], 'String');
            }
        }
        return obj;
    }

    /**
    * The capacity value.
    * @member {Number} value
    */
    value = undefined;
    /**
    * The unit type of given capacity, i.e. \"ETH\".
    * @member {String} unit
    */
    unit = undefined;
    /**
    * The formatted display value of the capacity, i.e. \"250.00 ETH\"
    * @member {String} displayValue
    */
    displayValue = undefined;








}


