/**
 * Aces Service API
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Argument from './Argument';





/**
* The ContractRequest model module.
* @module model/ContractRequest
* @version 0.1.0
*/
export default class ContractRequest {
    /**
    * Constructs a new <code>ContractRequest</code>.
    * @alias module:model/ContractRequest
    * @class
    * @param correlationId {String} Requestor generated globally unique identifier for correleating requests.
    */

    constructor(correlationId) {
        

        
        

        this['correlationId'] = correlationId;

        
    }

    /**
    * Constructs a <code>ContractRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContractRequest} obj Optional instance to populate.
    * @return {module:model/ContractRequest} The populated <code>ContractRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContractRequest();

            
            
            

            if (data.hasOwnProperty('correlationId')) {
                obj['correlationId'] = ApiClient.convertToType(data['correlationId'], 'String');
            }
            if (data.hasOwnProperty('arguments')) {
                obj['arguments'] = ApiClient.convertToType(data['arguments'], [Argument]);
            }
        }
        return obj;
    }

    /**
    * Requestor generated globally unique identifier for correleating requests.
    * @member {String} correlationId
    */
    correlationId = undefined;
    /**
    * @member {Array.<module:model/Argument>} arguments
    */
    arguments = undefined;








}


