<?php
/**
 * AcesServiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ArkAces\AcesServiceApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ArkAces\AcesServiceApi;

use \ArkAces\AcesServiceApi\Configuration;
use \ArkAces\AcesServiceApi\ApiException;
use \ArkAces\AcesServiceApi\ObjectSerializer;

/**
 * AcesServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArkAces\AcesServiceApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AcesServiceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for contractsIdGet
     *
     * Get Service Contract..
     *
     */
    public function testContractsIdGet()
    {
    }

    /**
     * Test case for contractsPost
     *
     * Create Service Contract.
     *
     */
    public function testContractsPost()
    {
    }

    /**
     * Test case for healthGet
     *
     * Get Health of node..
     *
     */
    public function testHealthGet()
    {
    }

    /**
     * Test case for rootGet
     *
     * Get Service Info..
     *
     */
    public function testRootGet()
    {
    }
}
