<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ArkAces\ServiceClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability.
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ArkAces\ServiceClient;

use \ArkAces\ServiceClient\Configuration;
use \ArkAces\ServiceClient\ApiException;
use \ArkAces\ServiceClient\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArkAces\ServiceClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for contractsIdGet
     *
     * Get Service Contract..
     *
     */
    public function testContractsIdGet()
    {
    }

    /**
     * Test case for contractsPost
     *
     * Create Service Contract.
     *
     */
    public function testContractsPost()
    {
    }

    /**
     * Test case for infoGet
     *
     * Get Service Info..
     *
     */
    public function testInfoGet()
    {
    }

    /**
     * Test case for statusGet
     *
     * Get Health of node..
     *
     */
    public function testStatusGet()
    {
    }
}
