/* 
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArkAces.ServiceClient.Client.SwaggerDateConverter;

namespace ArkAces.ServiceClient.Model
{
    /// <summary>
    /// Defines Feature
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Feature
    {
        
        /// <summary>
        /// Enum ArkSmartbridgePayable for "arkSmartbridgePayable"
        /// </summary>
        [EnumMember(Value = "arkSmartbridgePayable")]
        ArkSmartbridgePayable,
        
        /// <summary>
        /// Enum ArkReturnable for "arkReturnable"
        /// </summary>
        [EnumMember(Value = "arkReturnable")]
        ArkReturnable
    }

}
