/**
 * Aces Service API
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Capacity from './model/Capacity';
import Contract from './model/Contract';
import ContractRequest from './model/ContractRequest';
import FieldError from './model/FieldError';
import Health from './model/Health';
import Info from './model/Info';
import ModelInterface from './model/ModelInterface';
import NotFoundError from './model/NotFoundError';
import ValidationError from './model/ValidationError';
import AcesServiceApi from './arkaces-service-client/AcesServiceApi';


/**
* API_Specification_for_Aces_Services_for_blockchain_interoperability_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AcesServiceApi = require('index'); // See note below*.
* var xxxSvc = new AcesServiceApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AcesServiceApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AcesServiceApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AcesServiceApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Capacity model constructor.
     * @property {module:model/Capacity}
     */
    Capacity,

    /**
     * The Contract model constructor.
     * @property {module:model/Contract}
     */
    Contract,

    /**
     * The ContractRequest model constructor.
     * @property {module:model/ContractRequest}
     */
    ContractRequest,

    /**
     * The FieldError model constructor.
     * @property {module:model/FieldError}
     */
    FieldError,

    /**
     * The Health model constructor.
     * @property {module:model/Health}
     */
    Health,

    /**
     * The Info model constructor.
     * @property {module:model/Info}
     */
    Info,

    /**
     * The ModelInterface model constructor.
     * @property {module:model/ModelInterface}
     */
    ModelInterface,

    /**
     * The NotFoundError model constructor.
     * @property {module:model/NotFoundError}
     */
    NotFoundError,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The AcesServiceApi service constructor.
    * @property {module:arkaces-service-client/AcesServiceApi}
    */
    AcesServiceApi
};
