/*
 * Aces Service API
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Capacity
 */

public class Capacity {
  @SerializedName("value")
  private BigDecimal value = null;

  @SerializedName("unit")
  private String unit = null;

  @SerializedName("displayValue")
  private String displayValue = null;

  public Capacity value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * The capacity value.
   * @return value
  **/
  @ApiModelProperty(value = "The capacity value.")
  @JsonSerialize(using = ToStringSerializer.class)
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }

  public Capacity unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * The unit type of given capacity, i.e. \&quot;ETH\&quot;.
   * @return unit
  **/
  @ApiModelProperty(value = "The unit type of given capacity, i.e. \"ETH\".")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public Capacity displayValue(String displayValue) {
    this.displayValue = displayValue;
    return this;
  }

   /**
   * The formatted display value of the capacity, i.e. \&quot;250.00 ETH\&quot;
   * @return displayValue
  **/
  @ApiModelProperty(value = "The formatted display value of the capacity, i.e. \"250.00 ETH\"")
  public String getDisplayValue() {
    return displayValue;
  }

  public void setDisplayValue(String displayValue) {
    this.displayValue = displayValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Capacity capacity = (Capacity) o;
    return Objects.equals(this.value, capacity.value) &&
        Objects.equals(this.unit, capacity.unit) &&
        Objects.equals(this.displayValue, capacity.displayValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, unit, displayValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Capacity {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    displayValue: ").append(toIndentedString(displayValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

