# coding: utf-8

"""
    Aces Service API

    API Specification for Aces Services for blockchain interoperability. 

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import io.arkaces.service_client
from io.arkaces.service_client.rest import ApiException
from io.arkaces.service_client.models.info import Info


class TestInfo(unittest.TestCase):
    """ Info unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfo(self):
        """
        Test Info
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = io.arkaces.service_client.models.info.Info()
        pass


if __name__ == '__main__':
    unittest.main()
