# coding: utf-8

"""
    Aces Service API

    API Specification for Aces Services for blockchain interoperability. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import com.arkaces.aces_service_api
from com.arkaces.aces_service_api.rest import ApiException
from com.arkaces.aces_service_api.models.interface import Interface


class TestInterface(unittest.TestCase):
    """ Interface unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInterface(self):
        """
        Test Interface
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = com.arkaces.aces_service_api.models.interface.Interface()
        pass


if __name__ == '__main__':
    unittest.main()
