# coding: utf-8

"""
    Aces Service API

    API Specification for Aces Services for blockchain interoperability. 

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import io.arkaces.service_client
from io.arkaces.service_client.rest import ApiException
from io.arkaces.service_client.models.contract import Contract


class TestContract(unittest.TestCase):
    """ Contract unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContract(self):
        """
        Test Contract
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = io.arkaces.service_client.models.contract.Contract()
        pass


if __name__ == '__main__':
    unittest.main()
