/* 
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArkAces.AcesServiceApi.Api;
using ArkAces.AcesServiceApi.Model;
using ArkAces.AcesServiceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArkAces.AcesServiceApi.Test
{
    /// <summary>
    ///  Class for testing ContractRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContractRequestTests
    {
        // TODO uncomment below to declare an instance variable for ContractRequest
        //private ContractRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContractRequest
            //instance = new ContractRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContractRequest
        /// </summary>
        [Test]
        public void ContractRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContractRequest
            //Assert.IsInstanceOfType<ContractRequest> (instance, "variable 'instance' is a ContractRequest");
        }


        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Test]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }
        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Test]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }

    }

}
