/* 
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ArkAces.AcesServiceApi.Client;
using ArkAces.AcesServiceApi.Api;
using ArkAces.AcesServiceApi.Model;

namespace ArkAces.AcesServiceApi.Test
{
    /// <summary>
    ///  Class for testing AcesServiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AcesServiceApiTests
    {
        private AcesServiceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AcesServiceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AcesServiceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AcesServiceApi
            //Assert.IsInstanceOfType(typeof(AcesServiceApi), instance, "instance is a AcesServiceApi");
        }

        
        /// <summary>
        /// Test ContractsIdGet
        /// </summary>
        [Test]
        public void ContractsIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ContractsIdGet(id);
            //Assert.IsInstanceOf<Contract> (response, "response is Contract");
        }
        
        /// <summary>
        /// Test ContractsPost
        /// </summary>
        [Test]
        public void ContractsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ContractRequest contractRequest = null;
            //var response = instance.ContractsPost(contractRequest);
            //Assert.IsInstanceOf<Contract> (response, "response is Contract");
        }
        
        /// <summary>
        /// Test HealthGet
        /// </summary>
        [Test]
        public void HealthGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.HealthGet();
            //Assert.IsInstanceOf<Health> (response, "response is Health");
        }
        
        /// <summary>
        /// Test RootGet
        /// </summary>
        [Test]
        public void RootGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.RootGet();
            //Assert.IsInstanceOf<Info> (response, "response is Info");
        }
        
    }

}
