/**
 * Aces Service API
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AcesServiceApi);
  }
}(this, function(expect, AcesServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AcesServiceApi.Capacity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Capacity', function() {
    it('should create an instance of Capacity', function() {
      // uncomment below and update the code to test Capacity
      //var instane = new AcesServiceApi.Capacity();
      //expect(instance).to.be.a(AcesServiceApi.Capacity);
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instane = new AcesServiceApi.Capacity();
      //expect(instance).to.be();
    });

    it('should have the property unit (base name: "unit")', function() {
      // uncomment below and update the code to test the property unit
      //var instane = new AcesServiceApi.Capacity();
      //expect(instance).to.be();
    });

    it('should have the property displayValue (base name: "displayValue")', function() {
      // uncomment below and update the code to test the property displayValue
      //var instane = new AcesServiceApi.Capacity();
      //expect(instance).to.be();
    });

  });

}));
