<?php
/**
 * FeatureTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArkAces\ServiceClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability.
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ArkAces\ServiceClient;

/**
 * FeatureTest Class Doc Comment
 *
 * @category    Class */
// * @description Feature
/**
 * @package     ArkAces\ServiceClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FeatureTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Feature"
     */
    public function testFeature()
    {
    }
}
