/*
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package arkaces/service-client

type Argument struct {

	// Argument name matching a parameter in service contract schema.
	Name string `json:"name,omitempty"`

	// Arugment value.
	Value *interface{} `json:"value,omitempty"`
}
