/*
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package arkaces/service-client

type Capacity struct {

	// The capacity value.
	Value float32 `json:"value,omitempty"`

	// The unit type of given capacity, i.e. \"ETH\".
	Unit string `json:"unit,omitempty"`

	// The formatted display value of the capacity, i.e. \"250.00 ETH\"
	DisplayValue string `json:"displayValue,omitempty"`
}
