/*
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package arkaces/aces-service-api

type ContractRequest struct {

	// Requestor generated globally unique identifier for correleating requests.
	CorrelationId string `json:"correlationId"`

	Arguments *interface{} `json:"arguments,omitempty"`
}
