/*
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package arkaces/service-client

type Feature string

// List of Feature
const (
	ARK_SMARTBRIDGE_PAYABLE Feature = "arkSmartbridgePayable"
	ARK_RETURNABLE Feature = "arkReturnable"
)
