/*
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package arkaces/service-client

type Info struct {

	// Name of the contract service.
	Name string `json:"name,omitempty"`

	// Description of the contract service.
	Description string `json:"description,omitempty"`

	// Service usage instructions in markdown format.
	Instructions string `json:"instructions,omitempty"`

	Capacities []Capacity `json:"capacities,omitempty"`

	FlatFee string `json:"flatFee,omitempty"`

	PercentFee string `json:"percentFee,omitempty"`

	// Contract input schema in JSON Schema format.
	ContractSchema *interface{} `json:"contractSchema,omitempty"`

	Interfaces []ModelInterface `json:"interfaces,omitempty"`
}
