/*
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package arkaces/aces-service-api

type Interface string

// List of Interface
const (
	ARK_SMARTBRIDGE_PAYABLE ModelInterface = "arkSmartbridgePayable"
	ARK_RETURNABLE ModelInterface = "arkReturnable"
)
