/* 
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArkAces.ServiceClient.Api;
using ArkAces.ServiceClient.Model;
using ArkAces.ServiceClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArkAces.ServiceClient.Test
{
    /// <summary>
    ///  Class for testing Argument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ArgumentTests
    {
        // TODO uncomment below to declare an instance variable for Argument
        //private Argument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Argument
            //instance = new Argument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Argument
        /// </summary>
        [Test]
        public void ArgumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Argument
            //Assert.IsInstanceOfType<Argument> (instance, "variable 'instance' is a Argument");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
