/* 
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArkAces.ServiceClient.Api;
using ArkAces.ServiceClient.Model;
using ArkAces.ServiceClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArkAces.ServiceClient.Test
{
    /// <summary>
    ///  Class for testing Capacity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CapacityTests
    {
        // TODO uncomment below to declare an instance variable for Capacity
        //private Capacity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Capacity
            //instance = new Capacity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Capacity
        /// </summary>
        [Test]
        public void CapacityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Capacity
            //Assert.IsInstanceOfType<Capacity> (instance, "variable 'instance' is a Capacity");
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'DisplayValue'
        /// </summary>
        [Test]
        public void DisplayValueTest()
        {
            // TODO unit test for the property 'DisplayValue'
        }

    }

}
