/* 
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArkAces.ServiceClient.Api;
using ArkAces.ServiceClient.Model;
using ArkAces.ServiceClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArkAces.ServiceClient.Test
{
    /// <summary>
    ///  Class for testing Feature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeatureTests
    {
        // TODO uncomment below to declare an instance variable for Feature
        //private Feature instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Feature
            //instance = new Feature();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Feature
        /// </summary>
        [Test]
        public void FeatureInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Feature
            //Assert.IsInstanceOfType<Feature> (instance, "variable 'instance' is a Feature");
        }



    }

}
