/* 
 * Aces Service API
 *
 * API Specification for Aces Services for blockchain interoperability. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArkAces.ServiceClient.Api;
using ArkAces.ServiceClient.Model;
using ArkAces.ServiceClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArkAces.ServiceClient.Test
{
    /// <summary>
    ///  Class for testing Info
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InfoTests
    {
        // TODO uncomment below to declare an instance variable for Info
        //private Info instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Info
            //instance = new Info();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Info
        /// </summary>
        [Test]
        public void InfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Info
            //Assert.IsInstanceOfType<Info> (instance, "variable 'instance' is a Info");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Test]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'Capacities'
        /// </summary>
        [Test]
        public void CapacitiesTest()
        {
            // TODO unit test for the property 'Capacities'
        }
        /// <summary>
        /// Test the property 'FlatFee'
        /// </summary>
        [Test]
        public void FlatFeeTest()
        {
            // TODO unit test for the property 'FlatFee'
        }
        /// <summary>
        /// Test the property 'ContractSchema'
        /// </summary>
        [Test]
        public void ContractSchemaTest()
        {
            // TODO unit test for the property 'ContractSchema'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Test]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

    }

}
